// Family-friendly 5-letter words, suitable for all ages.
// Curated to avoid anything inappropriate for young children.
const WORDS = [
  "ACORN", "ADDED", "AFTER", "AGAIN", "AGENT", "ALERT", "ALIKE", "ALIVE",
  "ALLEY", "ALLOW", "ALONE", "ALONG", "ALTAR", "ANGEL", "ANGRY", "ANKLE",
  "ANNEX", "APART", "APPLE", "APPLY", "APRON", "ARROW", "ASKED", "ATLAS",
  "ATTIC", "AVAIL", "AVOID", "AWAKE", "AWARD", "AWARE", "AWFUL",

  "BACON", "BADGE", "BAGEL", "BANJO", "BANKS", "BASIC", "BASIN", "BATCH",
  "BEACH", "BEADS", "BEARS", "BEAST", "BEGAN", "BEGIN", "BEING", "BENCH",
  "BERRY", "BIBLE", "BIKES", "BIRDS", "BLACK", "BLADE", "BLAND", "BLANK",
  "BLAST", "BLAZE", "BLEAT", "BLEND", "BLESS", "BLIND", "BLOCK", "BLOOM",
  "BLOWN", "BOARD", "BOAST", "BONUS", "BOOST", "BOOTH", "BORED", "BOUND",
  "BOXER", "BRAVE", "BREAD", "BREAK", "BREAM", "BREED", "BRICK", "BRIDE",
  "BRING", "BRISK", "BROOK", "BROOM", "BROTH", "BROWN", "BRUSH", "BUDDY",
  "BUILD", "BUILT", "BULGE", "BUNCH", "BUNNY", "BURST", "BUSHY", "BUYER",

  "CABIN", "CAKES", "CAMEL", "CANDY", "CANOE", "CARDS", "CARRY", "CATCH",
  "CAUSE", "CAVES", "CEDAR", "CHAIN", "CHAIR", "CHALK", "CHARM", "CHART",
  "CHASE", "CHEAP", "CHECK", "CHEER", "CHESS", "CHEST", "CHICK", "CHIME",
  "CHIRP", "CLAMP", "CLANG", "CLANK", "CLASH", "CLASP", "CLASS", "CLEAN",
  "CLEAR", "CLICK", "CLIFF", "CLIMB", "CLING", "CLOCK", "CLOSE",
  "CLOTH", "CLOUD", "CLOWN", "COACH", "COAST", "COCOA", "COLOR", "COMIC",
  "COMET", "CORAL", "COUNT", "COVER", "CRANE", "CREAM", "CREEK",
  "CRISP", "CROSS", "CROWD", "CROWN", "CRUSH", "CRUST", "CUBIC", "CURVE",

  "DADDY", "DAISY", "DANCE", "DEALT", "DECOR", "DELTA", "DENSE",
  "DEPTH", "DERBY", "DEVIL", "DINER", "DISCO", "DITCH", "DIZZY", "DODGE",
  "DOING", "DOUGH", "DOWNY", "DRAFT", "DRAIN", "DRAMA", "DRANK", "DRAWN",
  "DREAM", "DRESS", "DRIFT", "DRINK", "DRIVE", "DROVE", "DRUMS", "DRYER",
  "DUNES", "DUSTY", "DWARF",

  "EAGLE", "EARLY", "EARTH", "EIGHT", "ELBOW", "EMOTE", "EMPTY", "ENJOY",
  "ENTRY", "EQUAL", "ESSAY", "EVADE", "EVENT", "EVERY", "EXACT", "EXCEL",
  "EXIST",

  "FABLE", "FAIRY", "FAITH", "FANCY", "FEAST", "FIELD", "FIFTY", "FIGHT",
  "FINAL", "FIRST", "FIXED", "FLAME", "FLASH", "FLEET", "FLICK",
  "FLOCK", "FLOOD", "FLOOR", "FLORA", "FLOSS", "FLOUR", "FLOWN",
  "FLUID", "FLUTE", "FOCUS", "FOGGY", "FORCE", "FORGE", "FORMS", "FORTH",
  "FOUND", "FRESH", "FROWN", "FROZE", "FRUIT", "FULLY",
  "FUNKY", "FUNNY", "FUZZY",

  "GAMES", "GIANT", "GIVEN", "GLADE", "GLASS", "GLEAM", "GLOBE",
  "GLOSS", "GLOVE", "GOING", "GRACE", "GRADE", "GRAIN", "GRAND",
  "GRANT", "GRAPE", "GRASP", "GRASS", "GREAT", "GREEN", "GRILL", "GRIND",
  "GROAN", "GROOM", "GROPE", "GROSS", "GROUP", "GROVE", "GROWL", "GROWN",
  "GRUEL", "GUARD", "GUIDE", "GUILD", "GUSTO",

  "HANDY", "HAPPY", "HAVEN", "HEART", "HEAVY", "HEDGE", "HELLO", "HELPS",
  "HERBS", "HERON", "HIGHS", "HILLS", "HIPPO", "HOBBY", "HOLLY", "HOMES",
  "HONEY", "HORSE", "HOTEL", "HOURS", "HOUSE", "HUMAN", "HUMID", "HUMOR",
  "HUSKY",

  "IDEAL", "INNER", "INPUT",

  "JOKER", "JOLLY", "JELLY", "JEWEL", "JOUST", "JUMBO", "JUMPY", "JUICY",
  "JUICE", "JUDGE",

  "KAYAK", "KITTY", "KNEEL", "KNELT", "KNIFE", "KNOCK", "KNOWN",

  "LABEL", "LANCE", "LARGE", "LATER", "LAUGH", "LAYER", "LEAFY", "LEARN",
  "LEAVE", "LEMON", "LEVEL", "LIGHT", "LIMIT", "LINER", "LIONS", "LIVER",
  "LOCAL", "LODGE", "LOGIC", "LOFTY", "LOOPS", "LOOSE", "LOVER", "LOYAL",
  "LUCKY", "LUNCH",

  "MAGIC", "MAKER", "MAPLE", "MARCH", "MANGO", "MATCH", "MAYOR", "MEDAL",
  "MELON", "MERRY", "MIGHT", "MINDS", "MISTY", "MIXED", "MONEY", "MONTH",
  "MOODY", "MOONS", "MOSSY", "MOUNT", "MOURN", "MOUSE", "MOVED", "MOVIE",
  "MUDDY", "MUNCH", "MUSIC", "MUSTY", "MYRRH",

  "NIFTY", "NIGHT", "NINJA", "NOBLE", "NORTH", "NOTED", "NOVEL", "NURSE",

  "OCEAN", "OFFER", "OFTEN", "OLIVE", "ONION", "OPERA", "ORBIT", "ORDER",
  "OTHER", "OTTER", "OUTER", "OWNED", "OWNER",

  "PACKS", "PAGES", "PAINT", "PANDA", "PANEL", "PANSY", "PAPER", "PARTY",
  "PATCH", "PEACE", "PEACH", "PEAKS", "PENNY", "PEPPY", "PERKY", "PIANO",
  "PLAIN", "PLACE", "PLAID", "PLANT", "PLATE", "PLAZA", "PLUCK", "PLUMB",
  "PLUME", "POLAR", "POPPY", "POWER", "PRESS", "PRICE", "PRIDE",
  "PRIME", "PRIZE", "PROOF", "PROUD", "PRUNE", "PUPPY", "PURSE",

  "QUEEN", "QUEST", "QUICK", "QUIET", "QUIRK", "QUOTA",

  "RABBI", "RADAR", "RADIO", "RAINY", "RAISE", "RALLY", "REACH", "READY",
  "REALM", "REBEL", "REEDS", "REIGN", "RELAX", "REPAY", "REPLY", "RIDER",
  "RIDGE", "RIGHT", "RISKY", "RIVAL", "RIVER", "ROAST", "ROBIN", "ROCKS",
  "ROCKY", "ROMAN", "ROOMY", "ROOTS", "ROPES", "ROSES", "ROUGH", "ROUND",
  "ROYAL", "RULER", "RUSTY",

  "SADLY", "SALAD", "SALTY", "SANDY", "SAUCE", "SAVED", "SCARY", "SCENE",
  "SCOUT", "SEDAN", "SEEDS", "SEIZE", "SENSE", "SEVEN", "SHADE", "SHAPE",
  "SHARK", "SHARP", "SHEEP", "SHEER", "SHELF", "SHELL", "SHIFT", "SHINE",
  "SHIRT", "SHOES", "SHOOT", "SHORT", "SHOUT", "SHOWN", "SHRUG", "SIGHT",
  "SILLY", "SINCE", "SIXTH", "SIXTY", "SKILL", "SLACK", "SLEEK", "SLEEP",
  "SLEET", "SLICE", "SLIDE", "SLOPE", "SMALL", "SMART", "SMILE", "SMOKE",
  "SNACK", "SNAIL", "SNAKE", "SNOWY", "SOLAR", "SOLID", "SOLVE", "SOUTH",
  "SPACE", "SPARK", "SPEAR", "SPEED", "SPELL", "SPEND", "SPICE", "SPIKE",
  "SPINE", "SPOKE", "SPOOK", "SPOON", "SPORT", "SPRAY", "SPREE", "SPRIG",
  "SQUID", "STACK", "STAMP", "STAND", "STARE", "START", "STASH",
  "STATE", "STAYS", "STEAL", "STEAM", "STEEL", "STEEP", "STEER", "STERN",
  "STICK", "STILL", "STOCK", "STOMP", "STONE", "STOOL", "STORK", "STORM",
  "STORY", "STOVE", "STUDY", "STUFF", "STYLE", "SUGAR", "SUNNY", "SUPER",
  "SWAMP", "SWARM", "SWEET", "SWIFT", "SWIRL", "SWOOP",

  "TABLE", "TAKEN", "TASTY", "TEARY", "THANK", "THICK", "THIRD", "THREE",
  "THREW", "THROW", "TIGER", "TITLE", "TOTAL", "TOUCH", "TOUGH",
  "TOWER", "TOWEL", "TRACK", "TRAIL", "TRAIN", "TRAIT", "TREAT", "TREND",
  "TRICK", "TRIED", "TROOP", "TRUST", "TRUTH", "TULIP", "TUMMY", "TUNER",
  "TWIST",

  "UNDER", "UNITY", "UNTIL", "UPPER", "UPSET", "USHER",

  "VALID", "VALUE", "VAPOR", "VAULT", "VICAR", "VIDEO", "VIGOR", "VIRAL",
  "VISIT", "VITAL", "VIVID", "VOCAL",

  "WADED", "WANDS", "WATCH", "WATER", "WEAVE", "WEDGE", "WHALE", "WHEAT",
  "WHEEL", "WHERE", "WHICH", "WHILE", "WHITE", "WHOLE", "WINDS", "WITTY",
  "WOMAN", "WOMEN", "WOODY", "WORLD", "WORRY", "WORTH", "WRITE",

  "YACHT", "YEARN", "YEARS", "YOUNG", "YOUTH",

  "ZEBRA", "ZESTY", "ZONES", "ZONAL"
].sort();
